server:
  port: 8081
  servlet:
    context-path: /system-a

spring:
  application:
    name: system-a
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: system-a-client
            client-secret: oHliFH21Y52oLqa5sXL1eUpq6P67HJKa
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/system-a/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo
            authorization-uri: http://localhost:8080/realms/demo/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/demo/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/demo/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/demo/protocol/openid-connect/certs
            user-name-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG